// Code generated by entc, DO NOT EDIT.

package style

const (
	// Label holds the string label denoting the style type in the database.
	Label = "style"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStyle holds the string denoting the style field in the database.
	FieldStyle = "style"
	// EdgeProducts holds the string denoting the products edge name in mutations.
	EdgeProducts = "products"
	// Table holds the table name of the style in the database.
	Table = "styles"
	// ProductsTable is the table that holds the products relation/edge.
	ProductsTable = "products"
	// ProductsInverseTable is the table name for the Product entity.
	// It exists in this package in order to avoid circular dependency with the "product" package.
	ProductsInverseTable = "products"
	// ProductsColumn is the table column denoting the products relation/edge.
	ProductsColumn = "style_id"
)

// Columns holds all SQL columns for style fields.
var Columns = []string{
	FieldID,
	FieldStyle,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
