// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/NutchaPK/test/ent/order"
	"github.com/NutchaPK/test/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescPaidDate is the schema descriptor for PaidDate field.
	orderDescPaidDate := orderFields[2].Descriptor()
	// order.DefaultPaidDate holds the default value on creation for the PaidDate field.
	order.DefaultPaidDate = orderDescPaidDate.Default.(func() time.Time)
}
