// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NutchaPK/test/ent/size"
)

// Size is the model entity for the Size schema.
type Size struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Size holds the value of the "Size" field.
	Size string `json:"Size,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SizeQuery when eager-loading is set.
	Edges SizeEdges `json:"edges"`
}

// SizeEdges holds the relations/edges for other nodes in the graph.
type SizeEdges struct {
	// Products holds the value of the products edge.
	Products []*Product `json:"products,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProductsOrErr returns the Products value or an error if the edge
// was not loaded in eager-loading.
func (e SizeEdges) ProductsOrErr() ([]*Product, error) {
	if e.loadedTypes[0] {
		return e.Products, nil
	}
	return nil, &NotLoadedError{edge: "products"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Size) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case size.FieldID:
			values[i] = new(sql.NullInt64)
		case size.FieldSize:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Size", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Size fields.
func (s *Size) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case size.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case size.FieldSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Size", values[i])
			} else if value.Valid {
				s.Size = value.String
			}
		}
	}
	return nil
}

// QueryProducts queries the "products" edge of the Size entity.
func (s *Size) QueryProducts() *ProductQuery {
	return (&SizeClient{config: s.config}).QueryProducts(s)
}

// Update returns a builder for updating this Size.
// Note that you need to call Size.Unwrap() before calling this method if this Size
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Size) Update() *SizeUpdateOne {
	return (&SizeClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the Size entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Size) Unwrap() *Size {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Size is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Size) String() string {
	var builder strings.Builder
	builder.WriteString("Size(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", Size=")
	builder.WriteString(s.Size)
	builder.WriteByte(')')
	return builder.String()
}

// Sizes is a parsable slice of Size.
type Sizes []*Size

func (s Sizes) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
