// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NutchaPK/test/ent/style"
)

// Style is the model entity for the Style schema.
type Style struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Style holds the value of the "Style" field.
	Style string `json:"Style,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StyleQuery when eager-loading is set.
	Edges StyleEdges `json:"edges"`
}

// StyleEdges holds the relations/edges for other nodes in the graph.
type StyleEdges struct {
	// Products holds the value of the products edge.
	Products []*Product `json:"products,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProductsOrErr returns the Products value or an error if the edge
// was not loaded in eager-loading.
func (e StyleEdges) ProductsOrErr() ([]*Product, error) {
	if e.loadedTypes[0] {
		return e.Products, nil
	}
	return nil, &NotLoadedError{edge: "products"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Style) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case style.FieldID:
			values[i] = new(sql.NullInt64)
		case style.FieldStyle:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Style", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Style fields.
func (s *Style) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case style.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case style.FieldStyle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Style", values[i])
			} else if value.Valid {
				s.Style = value.String
			}
		}
	}
	return nil
}

// QueryProducts queries the "products" edge of the Style entity.
func (s *Style) QueryProducts() *ProductQuery {
	return (&StyleClient{config: s.config}).QueryProducts(s)
}

// Update returns a builder for updating this Style.
// Note that you need to call Style.Unwrap() before calling this method if this Style
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Style) Update() *StyleUpdateOne {
	return (&StyleClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the Style entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Style) Unwrap() *Style {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Style is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Style) String() string {
	var builder strings.Builder
	builder.WriteString("Style(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", Style=")
	builder.WriteString(s.Style)
	builder.WriteByte(')')
	return builder.String()
}

// Styles is a parsable slice of Style.
type Styles []*Style

func (s Styles) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
