// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Gender is the predicate function for gender builders.
type Gender func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Size is the predicate function for size builders.
type Size func(*sql.Selector)

// Style is the predicate function for style builders.
type Style func(*sql.Selector)
